version: "3.7"

networks:
  rails:

services:
  app:
    build: .
    container_name: ruby_worksites_container
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app
      - bundle_path:/bundle
    environment:
      - BUNDLE_PATH=/bundle/vendor
    depends_on:
      - postgres
    networks:
      - rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: fish
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rails

volumes:
  bundle_path:
  postgres-data: