default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode

development:
  <<: *default
  database: tank_development
  host: postgres
  username: postgres
  password: fish

production:
  <<: *default
  database: tank_production
  url: <%= ENV.fetch('DATABASE_URL', '') %>
